IQCWeb.WebClient/Models/InspectionsViewModel.cs
using IQCWeb.DTO;
using IQCWeb.WebClient.Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IQCWeb.WebClient.Models
{
    public class InspectionsViewModel
    {
        public IPagedList<Inspections> Inspections { get; set; }

        public IEnumerable<Countries> Countries { get; set; }
        

        public PagingInfo PagingInfo { get; set; }
    }

}

IQCWeb.WebClient/Controllers/InspectionsController.cs
using IQCWeb.DTO;
using IQCWeb.WebClient.Helpers;
using IQCWeb.WebClient.Models;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IQCWeb.WebClient.Controllers
{
    public class InspectionsController : Controller
    {

        public async Task<ActionResult> Index(int? page = 1, string currentFilter = null, string searchString = null)
        {
            if (searchString == null)
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var client = IQCWebHttpClient.GetClient();

           
            var model = new InspectionsViewModel();

            var csResponse = await client.GetAsync("api/countries");

            if (csResponse.IsSuccessStatusCode)
            {
                string csContent = await csResponse.Content.ReadAsStringAsync();
                var lstCountries = JsonConvert
                    .DeserializeObject<IEnumerable<Countries>>(csContent);

                model.Countries = lstCountries;
            }
            else
            {
                return Content("An error occurred.");
            }
            HttpResponseMessage response;
            if (!String.IsNullOrEmpty(searchString))
            {
                response = await client.GetAsync("api/inspections?partNum=" + searchString + "&sort=InspID&page=" + page + "&pagesize = 10");
            }
            else
            {
                response = await client.GetAsync("api/inspections?sort=PartNum&page=" + page + "&pagesize = 10");
            }

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();

                var pagingInfo = HeaderParser.FindAndParsePagingInfo(response.Headers);

                var lstInspections = JsonConvert.DeserializeObject<IEnumerable<Inspections>>(content);


                var pagedInspectionsList = new StaticPagedList<Inspections>(lstInspections,
                    pagingInfo.CurrentPage,
                    pagingInfo.PageSize, pagingInfo.TotalCount);

                model.Inspections = pagedInspectionsList;
                model.PagingInfo = pagingInfo;

            }
            else
            {
                if (response.ReasonPhrase.Contains("Not Found"))
                {
                    return Content("Not Found");                    
                }
                else
                {
                    return Content("An error occurred.");
                }
            }


            return View(model);
           
        }

 
        // GET: Inspections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/inspections/" + id
            + "?fields=Countries, AVM, IIM, Employees, Locations, Molds, FirstPieceReports");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Inspections>(content);
                return View(model);
            }

            return Content("An error occurred");
        }

        // GET: Inspections/Create
 
        public async Task<ActionResult> Create()
        {
            await PopulateInspectorsDropDownList();
            await PopulateLocationsDropDownList();
            await PopulateCountriesDropDownList();

            return View();
        }

        // POST: Inspections/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Inspections inspection)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                
                var serializedItemToCreate = JsonConvert.SerializeObject(inspection);

                var response = await client.PostAsync("api/inspections",
                    new StringContent(serializedItemToCreate,
                        System.Text.Encoding.Unicode,
                        "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred.");
                }
            }
            catch
            {
                return Content("An error occurred.");
            }
        }

        // GET: Inspections/Edit/5
 
        public async Task<ActionResult> Edit(int id)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/inspections/" + id);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Inspections>(content);
                await PopulateInspectorsDropDownList(model.EmployeeCounter);
                await PopulateLocationsDropDownList(model.LocationID);
                await PopulateCountriesDropDownList(model.CountryID);
                return View(model);
            }

            return Content("An error occurred.");

        }

        // POST: Inspections/Edit/5   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Inspections inspection)
        {
            try
            {
                
                var client = IQCWebHttpClient.GetClient();
                
                // serialize & PUT
                var serializedItemToUpdate = JsonConvert.SerializeObject(inspection);

                var response = await client.PutAsync("api/inspections/" + id,
                    new StringContent(serializedItemToUpdate,
                    System.Text.Encoding.Unicode, "application/json"));


                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }

            }
            catch
            {
                return Content("An error occurred");
            }
        }
         

        // POST: Inspections/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                var response = await client.DeleteAsync("api/inspections/" + id);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }

            }
            catch
            {
                return Content("An error occurred");
            }
        }


        private async Task PopulateInspectorsDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/employees?empFunction=QCI");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstInspectors = JsonConvert.DeserializeObject<IEnumerable<Employees>>(content);
                ViewBag.EmployeeCounter = new SelectList(lstInspectors, "EmployeeCounter", "Name", selectedValue);
            }

                        
        }

        private async Task PopulateLocationsDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/locations");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstLocations = JsonConvert.DeserializeObject<IEnumerable<Locations>>(content);
                ViewBag.LocationID = new SelectList(lstLocations, "LocationID", "Location", selectedValue);
            }


        }

        private async Task PopulateCountriesDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/countries");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstCountries = JsonConvert.DeserializeObject<IEnumerable<Countries>>(content);
                ViewBag.CountryID = new SelectList(lstCountries, "CountryID", "Country", selectedValue);
            }


        }

       
    }
}

IQCWeb.WebClient/Controllers/MoldsController.cs
using IQCWeb.DTO;
using IQCWeb.WebClient.Helpers;
using IQCWeb.WebClient.Models;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IQCWeb.WebClient.Controllers
{
    public class MoldsController : Controller
    {
        // GET: Molds/Create
        public ActionResult Create(int inspID)
        {
            ViewBag.InspID = inspID;
            return View();
        }

        // POST: Molds/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Molds mold)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();


                var serializedItemToCreate = JsonConvert.SerializeObject(mold);

                var response = await client.PostAsync("api/molds",
                    new StringContent(serializedItemToCreate,
                        System.Text.Encoding.Unicode,
                        "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Details", "Inspections", new { id = mold.InspID });
                }
                else
                {
                    return Content("An error occurred.");
                }
            }
            catch
            {
                return Content("An error occurred.");
            }
        }

        // GET: Molds/Edit/5

        public async Task<ActionResult> Edit(int id)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/molds/" + id);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Molds>(content);
               
                return View(model);
            }

            return Content("An error occurred.");

        }

        // POST: Molds/Edit/5   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Molds mold)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                // serialize & PUT
                var serializedItemToUpdate = JsonConvert.SerializeObject(mold);

                var response = await client.PutAsync("api/molds/" + id,
                    new StringContent(serializedItemToUpdate,
                    System.Text.Encoding.Unicode, "application/json"));


                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Details", "Inspections", new { id = mold.InspID });
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch
            {
                return Content("An error occurred");
            }
        }


        // POST: Molds/Delete/5
        public async Task<ActionResult> Delete(int inspId, int id)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                var response = await client.DeleteAsync("api/molds/" + id);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Details", "Inspections", new { id = inspId });
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch
            {
                return Content("An error occurred");
            }
        }
    }
}

IQCWeb.WebClient/Views/Inspections/Create.cshtml
@model IQCWeb.DTO.Inspections

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a New Inspection</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.Label("Record Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.IsInc, "0", htmlAttributes: new { @class = "radio-inline", @checked = "checked"}) Incoming
                @Html.RadioButtonFor(model => model.IsInc, "1", htmlAttributes: new { @class = "radio-inline" }) InProcess
                @Html.ValidationMessageFor(model => model.IsInc, "", new { @class = "text-danger" })
            </div>       

        </div>

        <div class="form-group">
            @Html.Label("Part Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Date Inspected", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateInspected, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DateInspected, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Inspector", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeCounter", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeCounter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("QC In", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QC_In, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.QC_In, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("QC Out", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QC_Out, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.QC_Out, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MFR Part Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MfrPartNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MfrPartNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Revision", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Revision, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Revision, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("PO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Receiver #", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RcvrNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RcvrNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Receiver Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.RcvrDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Vendor ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VendorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VendorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Quantity Received", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyReceived, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyReceived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Sample Size", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SampleSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SampleSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("1st piece inspection?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.RadioButtonFor(model => model.FirstPce, "True", htmlAttributes: new { @class = "radio-inline" }) Yes
                @Html.RadioButtonFor(model => model.FirstPce, "False", htmlAttributes: new { @class = "radio-inline", @checked = "checked" }) No
                @Html.ValidationMessageFor(model => model.FirstPce, "", new { @class = "text-danger" })
            </div>

        </div>    
       

        <div class="form-group">
            @Html.Label("Country of Origin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.Label("Acceptance", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Accept, "True", htmlAttributes: new { @class = "radio-inline", @checked = "checked" }) PASS
                @Html.RadioButtonFor(model => model.Accept, "False", htmlAttributes: new { @class = "radio-inline" }) FAIL
                @Html.ValidationMessageFor(model => model.Accept, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.Label("Comments", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comments, 4, 50, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $('.datepicker').datepicker()
</script>

IQCWeb.WebClient/Views/Inspections/Details.cshtml
@model IQCWeb.DTO.Inspections


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Inspection Details</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Record Type
        </dt>
        <dd>
            @if (Model.IsInc != null)
            {
                if ((int)Model.IsInc > 0)
                {
                    <text>InProcess</text>
                }
                else
                {
                    <text>Incoming</text>
                }
            }
        </dd>

        <dt>
            Part Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNum)
        </dd>

        <dt>
            Part Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IIM.PartDesc)
        </dd>

        <dt>
          Date Inspected
        </dt>

        <dd>
            @Model.DateInspected.Value.ToString("d")
        </dd>

        <dt>
            Inspector
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employees.Name)
        </dd>

        <dt>
            QC In
        </dt>

        <dd>
            @Model.QC_In.Value.ToString("d")
        </dd>

        <dt>
            QC Out
        </dt>

        <dd>
            @Model.QC_Out.Value.ToString("d")
        </dd>


        <dt>
            Location
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locations.Location)
        </dd>


        <dt>
            Revision
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Revision)
        </dd>

        <dt>
            Qty Received
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtyReceived)
        </dd>

        <dt>
            Sample Size
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SampleSize)
        </dd>

        <dt>
            VendorID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VendorID)
        </dd>


        <dt>
            Vendor Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AVM.VendorName)
        </dd>

        <dt>
            Country
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Countries.Country)          

        </dd>

        <dt>
           Comments
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    
    <h4>Molds</h4>
    <p>
        @Html.ActionLink("Add Mold", "Create", "Molds", new { inspId = Model.InspID }, null)
    </p>

    <div id="divMolds" style="@(Model.Molds.Count == 0 ? "display:none" : "display:block")">
        <table class="table">
            <tr>
                <th>
                    Part Number
                </th>
                <th>
                    Mold Number
                </th>
                <th>
                    Number of Cavities
                </th>
                <th>
                    Resin Used
                </th>
                <th>
                    Mold Revision
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Molds)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PartNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MoldNum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumOfCavities)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ResinUsed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MoldRev)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Molds", new { inspId = item.InspID, id = item.MoldID }, null) |
                        @Html.ActionLink("Delete", "Delete", "Molds", new { inspId = item.InspID, id = item.MoldID }, null)
                    </td>

                </tr>
            }

        </table>
    </div>


    <h4>FPRs</h4>
    <p>
        @Html.ActionLink("Add FPR", "Create", "FirstPieceReports", new { inspId = Model.InspID }, null)
    </p>

    <div id="divFprs" style="@(Model.FirstPieceReports.Count == 0 ? "display:none" : "display:block")">
        <table class="table">
            <tr>
                <th>
                    FPR No.
                </th>
                <th>
                    FPR Date
                </th>
                <th>
                    Engineer Acceptance
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.FirstPieceReports)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FPR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FprDate, "ShortDateTime")
                    </td>
                    <td>
                        @if (item.AcceptMechEng != null)
                        {
                            if ((int)item.AcceptMechEng == 1)
                            {
                                <text>Accept. Part meet spec.</text>
                            }
                            else if ((int)item.AcceptMechEng > 0)
                            {
                                <text>Reject</text>
                            }
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "FirstPieceReports", new { inspId = item.InspID, id = item.FPR_ID}, null) |
                        @Html.ActionLink("Delete", "Delete", "FirstPieceReports", new { inspId = item.InspID, id = item.FPR_ID }, null)
                    </td>

                </tr>
            }

        </table>
    </div>


   
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>