IQCWeb.WebClient/Controllers/InspectionsController.cs
using IQCWeb.DTO;
using IQCWeb.WebClient.Helpers;
using IQCWeb.WebClient.Models;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IQCWeb.WebClient.Controllers
{
    public class InspectionsController : Controller
    {

        public async Task<ActionResult> Index(int? page = 1, string currentFilter = null, string searchString = null)
        {
            if (searchString == null)
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var client = IQCWebHttpClient.GetClient();

           
            var model = new InspectionsViewModel();

            var csResponse = await client.GetAsync("api/countries");

            if (csResponse.IsSuccessStatusCode)
            {
                string csContent = await csResponse.Content.ReadAsStringAsync();
                var lstCountries = JsonConvert
                    .DeserializeObject<IEnumerable<Countries>>(csContent);

                model.Countries = lstCountries;
            }
            else
            {
                return Content("An error occurred.");
            }
            HttpResponseMessage response;
            if (!String.IsNullOrEmpty(searchString))
            {
                response = await client.GetAsync("api/inspections?partNum=" + searchString + "&sort=InspID&page=" + page + "&pagesize = 10");
            }
            else
            {
                response = await client.GetAsync("api/inspections?sort=PartNum&page=" + page + "&pagesize = 10");
            }

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();

                var pagingInfo = HeaderParser.FindAndParsePagingInfo(response.Headers);

                var lstInspections = JsonConvert.DeserializeObject<IEnumerable<Inspections>>(content);


                var pagedInspectionsList = new StaticPagedList<Inspections>(lstInspections,
                    pagingInfo.CurrentPage,
                    pagingInfo.PageSize, pagingInfo.TotalCount);

                model.Inspections = pagedInspectionsList;
                model.PagingInfo = pagingInfo;

            }
            else
            {
                if (response.ReasonPhrase.Contains("Not Found"))
                {
                    return Content("Not Found");                    
                }
                else
                {
                    return Content("An error occurred.");
                }
            }


            return View(model);
           
        }

 
        // GET: Inspections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/inspections/" + id
            + "?fields=Countries, AVM, IIM, Employees, Locations, Molds, FirstPieceReports");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Inspections>(content);
                return View(model);
            }

            return Content("An error occurred");
        }

        // GET: Inspections/Create
 
        public async Task<ActionResult> Create()
        {
            await PopulateInspectorsDropDownList();
            await PopulateLocationsDropDownList();
            await PopulateCountriesDropDownList();

            return View();
        }

        // POST: Inspections/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Inspections inspection)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                
                var serializedItemToCreate = JsonConvert.SerializeObject(inspection);

                var response = await client.PostAsync("api/inspections",
                    new StringContent(serializedItemToCreate,
                        System.Text.Encoding.Unicode,
                        "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred.");
                }
            }
            catch
            {
                return Content("An error occurred.");
            }
        }

        // GET: Inspections/Edit/5
 
        public async Task<ActionResult> Edit(int id)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/inspections/" + id);

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var model = JsonConvert.DeserializeObject<Inspections>(content);
                await PopulateInspectorsDropDownList(model.EmployeeCounter);
                await PopulateLocationsDropDownList(model.LocationID);
                await PopulateCountriesDropDownList(model.CountryID);
                return View(model);
            }

            return Content("An error occurred.");

        }

        // POST: Inspections/Edit/5   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Inspections inspection)
        {
            try
            {
                
                var client = IQCWebHttpClient.GetClient();
                
                // serialize & PUT
                var serializedItemToUpdate = JsonConvert.SerializeObject(inspection);

                var response = await client.PutAsync("api/inspections/" + id,
                    new StringContent(serializedItemToUpdate,
                    System.Text.Encoding.Unicode, "application/json"));


                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }

            }
            catch
            {
                return Content("An error occurred");
            }
        }
         

        // POST: Inspections/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var client = IQCWebHttpClient.GetClient();

                var response = await client.DeleteAsync("api/inspections/" + id);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }

            }
            catch
            {
                return Content("An error occurred");
            }
        }


        private async Task PopulateInspectorsDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/employees?empFunction=QCI");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstInspectors = JsonConvert.DeserializeObject<IEnumerable<Employees>>(content);
                ViewBag.EmployeeCounter = new SelectList(lstInspectors, "EmployeeCounter", "Name", selectedValue);
            }

                        
        }

        private async Task PopulateLocationsDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/locations");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstLocations = JsonConvert.DeserializeObject<IEnumerable<Locations>>(content);
                ViewBag.LocationID = new SelectList(lstLocations, "LocationID", "Location", selectedValue);
            }


        }

        private async Task PopulateCountriesDropDownList(object selectedValue = null)
        {
            var client = IQCWebHttpClient.GetClient();

            HttpResponseMessage response = await client.GetAsync("api/countries");

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var lstCountries = JsonConvert.DeserializeObject<IEnumerable<Countries>>(content);
                ViewBag.CountryID = new SelectList(lstCountries, "CountryID", "Country", selectedValue);
            }


        }

       
    }
}

IQCWeb.WebClient/Views/IncomingDMR/Create.cshtml
@model IQCWeb.DTO.IncomingDMR

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create a New FPR</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
       <div class="form-group">
            @Html.Label("DMR Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DmrDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DmrDate, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.Label("Reason", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.DropDownList("Reason_ID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Reason_ID, "", new { @class = "text-danger" })
            </div>
        </div>
        
      
        <div class="form-group">
            @Html.Label("Approved By", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApprovedBy", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApprovedBy, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            @Html.Label("Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Engineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Engineering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MFR Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MfrEngineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MfrEngineering, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Prod Control", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdControl", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdControl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchasing", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Purchasing", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Purchasing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("QA Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QAEngineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QAEngineering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MRB Coordinator", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MrbCoordinator", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MrbCoordinator, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Disposition Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DispDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DispDate, "", new { @class = "text-danger" })
            </div>
        </div>
               

     
        <div class="form-group">
            @Html.Label("Edistro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Edistro, 4, 50, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edistro, "", new { @class = "text-danger" })
            </div>
        </div>
                      
       
        <div class="form-group">
            @Html.Label("Sample Qty", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyDefs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyDefs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Qty Received", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyRejected, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyRejected, "", new { @class = "text-danger" })
            </div>
        </div>


        

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $('.datepicker').datepicker()
</script>

IQCWeb.WebClient/Views/IncomingDMR/Details.cshtml
@model IQCWeb.WebClient.Models.DmrViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DMR</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt >
            DMR No.
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.DMR)
        </dd>

        <dt>
            DMR Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.DmrDate, "ShortDateTime")
        </dd>

        <dt>
            Reason
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.Reasons.ReasonCode)
        </dd>
              
       
        <dt>
            Approved By
        </dt>

        <dd>
            @if (Model.DMR.ApprovedBy != null && Model.DMR.ApprovedBy != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                .First(cs => cs.EmployeeCounter == Model.DMR.ApprovedBy).Name)
            }
        </dd>


        <dt>
            Engineering
        </dt>

        <dd>
            @if (Model.DMR.Engineering != null && Model.DMR.Engineering != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.Engineering).Name)
            }
        </dd>

        <dt>
            MFR Engineering
        </dt>

        <dd>
            @if (Model.DMR.MfrEngineering != null && Model.DMR.MfrEngineering != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.MfrEngineering).Name)
            }
        </dd>

        <dt>
            Prod Control
        </dt>

        <dd>
            @if (Model.DMR.ProdControl != null && Model.DMR.ProdControl != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.ProdControl).Name)
            }
        </dd>

        <dt>
            Purchasing
        </dt>

        <dd>
            @if (Model.DMR.Purchasing != null && Model.DMR.Purchasing != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.Purchasing).Name)
            }
        </dd>

        <dt>
            QA Engineering
        </dt>

        <dd>
            @if (Model.DMR.QAEngineering!= null && Model.DMR.QAEngineering != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.QAEngineering).Name)
            }
        </dd>

        <dt>
            MRB Coordinator
        </dt>

        <dd>
            @if (Model.DMR.MrbCoordinator != null && Model.DMR.MrbCoordinator != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                    .First(cs => cs.EmployeeCounter == Model.DMR.MrbCoordinator).Name)
            }
        </dd>



        <dt>
            Disposition Date
        </dt>

        <dd>
            @{DateTime DefaultDate = new DateTime(1950, 1, 1);}
            @if (Model.DMR.DispDate != null && Model.DMR.DispDate != DefaultDate)
            {
                @Html.DisplayFor(model => model.DMR.DispDate, "ShortDateTime")
            }
        </dd>

            

        <dt>
            Edistro
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.Edistro)
        </dd>

        <dt>
           Sample Qty
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.QtyDefs)
        </dd>

        <dt>
            Qty Received
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMR.QtyRejected)
        </dd>

          



    </dl>

</div>
<p>
    @Html.ActionLink("Inspection Details", "Details", "Inspections", new { id = Model.DMR.InspID }, null)
    <p></p>
    @Html.ActionLink("Back to List", "Index")
</p>

IQCWeb.WebClient/Views/IncomingDMR/Edit.cshtml
@model IQCWeb.DTO.IncomingDMR

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DMR</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DMR_ID)
        @Html.HiddenFor(model => model.InspID)
          

        <div class="form-group">
            @Html.Label("DMR No", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DisplayFor(model => model.DMR)
               @*@Html.TextBoxFor(model => model.DMR, new { @readonly = "readonly", @class = "form-control" })*@
            </div>
        </div>


        <div class="form-group">
            @Html.Label("DMR Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DmrDate, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.DmrDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Reason", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Reason_ID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Reason_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.Label("Approved By", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApprovedBy", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApprovedBy, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Engineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Engineering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MFR Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MfrEngineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MfrEngineering, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Prod Control", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdControl", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdControl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchasing", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Purchasing", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Purchasing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("QA Engineering", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QAEngineering", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QAEngineering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MRB Coordinator", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MrbCoordinator", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MrbCoordinator, "", new { @class = "text-danger" })
            </div>
        </div>


        
        <div class="form-group">
            @Html.Label("Disposition Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DispDate, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker" })
                @Html.ValidationMessageFor(model => model.DispDate, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.Label("Edistro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Edistro, 4, 50, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edistro, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.Label("Sample Qty", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyDefs, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyDefs, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Qty Received", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QtyRejected, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QtyRejected, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Quality Notification", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QualityNotification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QualityNotification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



<script type="text/javascript">
    $('.datepicker').datepicker()
</script>

IQCWeb.WebClient/Views/IncomingDMR/Index.cshtml
@model IQCWeb.WebClient.Models.DmrViewModel

@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Incoming DMRs</h2>

<p>    
</p>
<table class="table">
    <tr>
        <th>
           Part Number
        </th>
        <th>
            DMR No.
        </th>
        <th>
            DMR Date
        </th>
        <th>
            Reason
        </th>
                      
        <th>
            Approved By
        </th>
        <th>
            Disposition Date 
        </th>    
       
      
        <th></th>
    </tr>

@foreach (var item in Model.PagedIncomingDMR)
{
    <tr>
        <td>
           @Html.DisplayFor(modelItem => item.Inspections.PartNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DMR)
        </td>
        <td>            
            @if (item.DmrDate != null)
            {
                @Html.DisplayFor(modelItem => item.DmrDate, "ShortDateTime")
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reasons.ReasonCode)
        </td>
       
       
        <td>
            @if (item.ApprovedBy != null && item.ApprovedBy != 0)
            {
                @((Model.Employees as List<IQCWeb.DTO.Employees>)
                                .First(cs => cs.EmployeeCounter == item.ApprovedBy).Name)
            }
        </td>
        <td>
            @if (item.DispDate != null)
            {
                @Html.DisplayFor(modelItem => item.DispDate, "ShortDateTime")
            }
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.DMR_ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.DMR_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.DMR_ID }) 
           
        </td>
    </tr>
}

</table>

@(Model.PagingInfo.CurrentPage) of @Model.PagingInfo.TotalPages


@Html.PagedListPager(Model.PagedIncomingDMR, page => Url.Action("Index", new { page }))